version: '3'

services:
  composer:
    image: composer
    volumes:
      - .:/var/www/html/
  php:
    build: ./
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
